name: run gsw_check (clang-cl)

on:
  pull_request:
  push:
    #branches: [master]
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Tests
      shell: bash
      run: |
        make -f Makefile-clang-cl && ./gsw_check
